theme: jekyll-theme-minimal
#theme: minima
title: Skolprogrammering med miljödata
description: Programmeringsövningar med satellitdata och annan miljödata för högstadium och gymnasium.
google_analytics: UA-166127929-1
#header_pages:
#  - exercises/README.md
